### ISSUE TITLE
Oversized device in Custom style guide

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-ios#3]
In Firefox 39, the “[Custom style](https://www.mapbox.com/mapbox-gl-ios/examples/custom-style/)” page has a comically bloated iPhone:

![bloat](https://cloud.githubusercontent.com/assets/1231218/7503054/23ddba74-f3f5-11e4-9de1-41dfa5b49568.png)

If I nix the `display: inline-block` from `.device`, all is well.

The problem does not reproduce in Safari 8.

/cc @katydecorah

**Comment by katydecorah** [comment]
Bloated iPhone or iPad? :wink: I forgot to resize the images, grabbing now...
